// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID           int64            `json:"id"`
	UserID       pgtype.Int4      `json:"userId"`
	Title        string           `json:"title"`
	Content      string           `json:"content"`
	StartingTime pgtype.Timestamp `json:"startingTime"`
	EndingTime   pgtype.Timestamp `json:"endingTime"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}
